In [51]:
import numpy as np

In [2]:
a=[1,2,3,4]
type(a)

list

In [3]:
b=np.array(a)
b

array([1, 2, 3, 4])

In [4]:
a=[[1,2,3],[4,5,6],[7,8,9]]
b=np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
print("total shape =",b.shape)
print("total dimension =",b.ndim)

total shape = (3, 3)
total dimension = 2



# pre-define function in numpy

In [8]:
#1. zeros()==> by function we can create an array with all the values zero

a=np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [9]:
a=np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
a.ndim

2

In [18]:
#2. ones()==> by this method we can crdeate an array with all the 1.
a=np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
a=np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
a.ndim

2

In [17]:
a.shape

(3, 4)

In [20]:
a=np.ones(((1,2,3)))
a

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [21]:
a.ndim

3

In [22]:
#3. eye() ==> by this method we can create an array in which digonal element are 1 and rest are 0.
a=np.eye(3,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [23]:
a=np.eye(4,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
# 4 diag()==> 
a=np.diag([1,56,78,90])
a

array([[ 1,  0,  0,  0],
       [ 0, 56,  0,  0],
       [ 0,  0, 78,  0],
       [ 0,  0,  0, 90]])

In [37]:
#5. random module
# (a). ranint()

a=np.random.randint(1,10,3)
a

array([5, 3, 4])

In [44]:
a=int(input("Enter start = "))
b=int(input("Enter end = "))
c=int(input("Enter number of values = "))
n=np.random.randint(a,b,c)
print(f"The {c} random number between {a} and {b} are = {n}")

Enter start = 1
Enter end = 10
Enter number of values = 4
The 4 random number between 1 and 10 are = [1 4 1 8]


In [46]:
# (b).rand()==> it will generate random number between 0 to 1
a=np.random.rand(5)
a

array([0.19009353, 0.84249514, 0.55905471, 0.08069801, 0.10458657])

In [47]:
a.shape

(5,)

In [51]:
a.ndim

2

In [52]:
a=np.random.rand(2,3)
a

array([[0.42605358, 0.84493602, 0.17729106],
       [0.72670366, 0.10574733, 0.33607399]])

In [53]:
a.shape

(2, 3)

In [54]:
a.ndim

2

In [58]:
# Reshape ==> n(rows)*n(columns) =n(total)
a=np.random.randint(1,60,12)
print("1,12 =",a.reshape(1,12))
print()
print("2,6 =",a.reshape(2,6))
print()
print("3,4 =",a.reshape(3,4))
print()
print("4,3 =",a.reshape(4,3))
print()
print("6,2 =",a.reshape(6,2))
print()
print("12,1 =",a.reshape(12,1))

1,12 = [[26 51 46 45  6  5 35 30 46 44 14 17]]

2,6 = [[26 51 46 45  6  5]
 [35 30 46 44 14 17]]

3,4 = [[26 51 46 45]
 [ 6  5 35 30]
 [46 44 14 17]]

4,3 = [[26 51 46]
 [45  6  5]
 [35 30 46]
 [44 14 17]]

6,2 = [[26 51]
 [46 45]
 [ 6  5]
 [35 30]
 [46 44]
 [14 17]]

12,1 = [[26]
 [51]
 [46]
 [45]
 [ 6]
 [ 5]
 [35]
 [30]
 [46]
 [44]
 [14]
 [17]]


# principal of -1

In [61]:
a=a.reshape(-1,3)
a

array([[26, 51, 46],
       [45,  6,  5],
       [35, 30, 46],
       [44, 14, 17]])

In [62]:
a=a.reshape(-1,4)
a

array([[26, 51, 46, 45],
       [ 6,  5, 35, 30],
       [46, 44, 14, 17]])

In [63]:
a=a.reshape(-1,6)
a

array([[26, 51, 46, 45,  6,  5],
       [35, 30, 46, 44, 14, 17]])

In [64]:
a=a.reshape(-1,2)
a

array([[26, 51],
       [46, 45],
       [ 6,  5],
       [35, 30],
       [46, 44],
       [14, 17]])

In [76]:
np.random.seed(21)
a=np.random.randint(1,10,3)
a

array([9, 5, 1])

In [79]:
np.random.seed(22)
a=np.random.randint(1,10,3)
a

array([6, 5, 1])

In [58]:
a=np.array([1,2,3,4]).reshape(2,2)
b=np.array([5,6,7,8]).reshape(2,2)

In [59]:
a+b

array([[ 6,  8],
       [10, 12]])

In [60]:
a*b

array([[ 5, 12],
       [21, 32]])

In [61]:
a.dot(b)

array([[19, 22],
       [43, 50]])

### Assignment

1. Difference b/w mutable and immutable with example
2. Difference b/w list and tuple [minimum 4 ex]
3. Difference b/w map and filter and lambda [real life usecase]
   given age if 18 plus true else false by using filter fun
4. difference b/w strip, split, isalpha, isdigit, isalnum [example with working process]


# given age if 18 plus true else false by using filter fun

In [7]:
ages = [16, 20, 14, 25, 18, 30]
filterage = list(filter(lambda age: age >= 18, ages))
result=[]
for age in ages:
    if age >= 18:
        result.append(True)
    else:
        result.append(False)
print(filterage)
print(result)

[20, 25, 18, 30]
[False, True, False, True, True, True]


# 1. Difference b/w mutable and immutable with example

# 2. Difference b/w list and tuple [minimum 4 ex]

In [63]:
fruits_list = ["apple", "banana", "cherry"]
fruits_list[0] = "orange"
fruits_list

['orange', 'banana', 'cherry']

In [64]:
fruits_tuple = ("apple", "banana", "cherry")
fruits_tuple[0] = "orange"

TypeError: 'tuple' object does not support item assignment

In [65]:
fruits_list.append("grape")
fruits_list.remove("banana")
fruits_list

['orange', 'cherry', 'grape']

In [66]:
fruits_tuple + ("grape", "orange")

('apple', 'banana', 'cherry', 'grape', 'orange')

# 3. Difference b/w map and filter and lambda [real life usecase]

# 4. difference b/w strip, split, isalpha, isdigit, isalnum [example with working process]

In [5]:
a="hello world"
a.split()
#split with comma

['hello', 'world']

In [37]:
a="       hello world"
a.strip()
#remove space from start and end

'hello world'

In [42]:
a="hello"
a.isalpha()
#check al element are alphabet

True

In [44]:
a="1234"
a.isdigit()
#check all element are num

True

In [49]:
a="helloworld"
a.isalnum()
#check if element are num or alphabet

False